# -*- coding: utf-8 -*-
"""
Django settings for myblog project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(__file__))
PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%@jh)w*i1u2iuq%mn^-c*(hu13had_x-u0v2dep&mj__#k1v70'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.home'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'myblog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(PROJECT_ROOT, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myblog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
KEY_PREFIX = 'hl'
SENTINEL_LOCATION = ['10.101.95.57:26379', '10.189.195.143:26379', '10.101.82.133:26379']
REDIS_BACKEND = "libs.djangos.cache.redis_backend.RedisCache"
OCS_BACKEND = "django_bmemcached.memcached.BMemcached"
OCS_BACKEND_OTHER = "libs.cache_backend.NoCloseMemcachedBackend"
REDIS_LOCATION_DEFAULT = "10.218.144.33:6379"
REDIS_LOCATION_DEFAULT_PASSWORD = "42e4b12e576a11e5:123456_78a1A"
CACHE_SOCKET_TIMEOUT = 0.5
CACHES = {
    #"default": {
    #    "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    #},
    'default': {
        'BACKEND': 'redis_cache.cache.RedisCache',
        'LOCATION': '127.0.0.1:6379',
        'KEY_PREFIX': KEY_PREFIX,
        'OPTIONS': {
            'MASTER_NAME': 'mymaster',
            'DB': 2,
            'READ_SLAVE': False,
        }
    },
     "kvs": {
        "BACKEND": 'redis_cache.cache.RedisCache',
        "LOCATION": REDIS_LOCATION_DEFAULT,
        "TIMEOUT": 300,
        "KEY_PREFIX": KEY_PREFIX,
        "OPTIONS": {
            "DB": 0,
            "PASSWORD": REDIS_LOCATION_DEFAULT_PASSWORD,
            'POOL_KWARGS': {
                'socket_timeout': CACHE_SOCKET_TIMEOUT,
                'socket_connect_timeout': CACHE_SOCKET_TIMEOUT
            },
        }
    },
    'memcached': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
        'KEY_PREFIX': KEY_PREFIX,
    },
    'ocs': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': ['d37bf52fa23a4bab.m.cnhzaligrpzmfpub001.ocs.aliyuncs.com:11211'],
        'TIMEOUT': 3600,
        'OPTIONS': {
            'username': 'd37bf52fa23a4bab',
            'password': '2015aos_debug',
        }
    },
    'ali_ocs': {
        'BACKEND': OCS_BACKEND_OTHER,
        'LOCATION': ['d37bf52fa23a4bab.m.cnhzaligrpzmfpub001.ocs.aliyuncs.com:11211'],
        'TIMEOUT': 3600,
        'OPTIONS': {
            'username': 'd37bf52fa23a4bab',
            'password': '2015aos_debug',
        }
    }
}


# celery config start
BROKER_URL = 'redis://@localhost:6379/0'
BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}
CELERY_RESULT_BACKEND = 'redis://@localhost:6379/1'
BROKER_TRANSPORT_OPTIONS = {'fanout_prefix': True}
